pipeline {
  agent {
    docker {
      image 'node:26-alpine'
      alwaysPull true
    }
  }
  stages {
    stage('Check Versions') {
      steps {
        sh 'node --version'
        sh 'npm --version'
      }
    }
    stage('Install Dependencies') {
      steps {
        sh 'npm ci'
      }
    }
    stage('Build') {
      steps {
        sh 'npm run build'
      }
    }
    stage('Test') {
      steps {
        sh 'npm test'
      }
    }
  }
}
