pipeline {
  agent {
    docker {
      image 'node:24-alpine'   // or node:26-alpine
      alwaysPull true
    }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
        sh 'npm --version'
      }
    }
  }
}
